### ISSUE TITLE
Add asSmalltalk to TF_Tensor

### ISSUE THREAD

**Issue by jburroni** [Cuis-Smalltalk/Machine-Learning#13]
TF_Tensor knows it's type, so it would be a good idea to add this method.
This should avoid some issues. For instance, if we do asInt32s to a 64 bits tensor, the results is incorrectly (and very hard to detect)

**Comment by gerasdf** [comment]
I think I'd call it #asArray? I was just doing it yesterday :-)
I'll commit after we merge !12

**Comment by gerasdf** [comment]
ok, done in 65d587fb6ceabd2019e768c0436a510f93c5e851. I first called it #asArray, but realized a single scalar is also a possible answer, so I renamed it to #asNumbers, and that's how I left it.
